-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 20:05:55 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `mydb`.`melis_cms_news_comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`melis_cms_news_comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`melis_cms_news_comments` (
  `ncom_id` INT NOT NULL AUTO_INCREMENT COMMENT 'Comment\'s id',
  `ncom_status` INT NOT NULL COMMENT 'Status of the account (active / inactive)',
  `ncom_validated` INT NOT NULL COMMENT '1/0 If the comment is validated, default 0',
  `ncom_news_id` INT NOT NULL COMMENT 'News Id of the comment',
  `ncom_default_name` VARCHAR(50) NULL COMMENT 'Name of the comment when no account linked',
  `ncom_comment_text` TEXT NOT NULL COMMENT 'Text of the comment',
  `ncom_date_creation` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Creation date of the comment',
  PRIMARY KEY (`ncom_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
